<?php

return [
    'atlet' => [
        'label' => 'Atlet',
        'model' => \App\Models\Atlet::class,
        'storage_dir' => 'atlets',
        'route_index' => 'admin.atlet.index',
        'headers' => [
            'kode_cabor' => 'Kode Cabor *',
            'name' => 'Nama Lengkap *',
            'birth_date' => 'Tanggal Lahir (YYYY-MM-DD)',
            'gender' => 'Jenis Kelamin (laki-laki/perempuan)',
            'phone' => 'Telepon',
            'email' => 'Email',
            'address' => 'Alamat',
            'bio' => 'Bio',
            'is_active' => 'Aktif (ya/tidak)',
        ],
        'example' => [
            'kode_cabor' => 'CAB-2026-001',
            'name' => 'Budi Santoso',
            'birth_date' => '2010-05-15',
            'gender' => 'laki-laki',
            'phone' => '08123456789',
            'email' => 'budi@email.com',
            'address' => 'Kec. Curup',
            'bio' => '',
            'is_active' => 'ya',
        ],
    ],
    'pelatih' => [
        'label' => 'Pelatih',
        'model' => \App\Models\Pelatih::class,
        'storage_dir' => 'pelatihs',
        'route_index' => 'admin.pelatih.index',
        'headers' => [
            'kode_cabor' => 'Kode Cabor *',
            'name' => 'Nama Lengkap *',
            'license_number' => 'No. Lisensi',
            'level' => 'Level',
            'phone' => 'Telepon',
            'email' => 'Email',
            'bio' => 'Bio',
            'is_active' => 'Aktif (ya/tidak)',
        ],
        'example' => [
            'kode_cabor' => 'CAB-2026-001',
            'name' => 'Andi Pelatih',
            'license_number' => 'LIS-001',
            'level' => 'Nasional',
            'phone' => '08123456789',
            'email' => 'andi@email.com',
            'bio' => '',
            'is_active' => 'ya',
        ],
    ],
    'wasit' => [
        'label' => 'Wasit',
        'model' => \App\Models\Wasit::class,
        'storage_dir' => 'wasits',
        'route_index' => 'admin.wasit.index',
        'headers' => [
            'kode_cabor' => 'Kode Cabor *',
            'name' => 'Nama Lengkap *',
            'license_number' => 'No. Lisensi',
            'level' => 'Level',
            'phone' => 'Telepon',
            'is_active' => 'Aktif (ya/tidak)',
        ],
        'example' => [
            'kode_cabor' => 'CAB-2026-001',
            'name' => 'Citra Wasit',
            'license_number' => 'WST-01',
            'level' => 'Provinsi',
            'phone' => '08123456789',
            'is_active' => 'ya',
        ],
    ],
    'juri' => [
        'label' => 'Juri',
        'model' => \App\Models\Juri::class,
        'storage_dir' => 'juris',
        'route_index' => 'admin.juri.index',
        'headers' => [
            'kode_cabor' => 'Kode Cabor *',
            'name' => 'Nama Lengkap *',
            'license_number' => 'No. Lisensi',
            'level' => 'Level',
            'phone' => 'Telepon',
            'is_active' => 'Aktif (ya/tidak)',
        ],
        'example' => [
            'kode_cabor' => 'CAB-2026-001',
            'name' => 'Dewi Juri',
            'license_number' => 'JRI-01',
            'level' => 'Kabupaten',
            'phone' => '08123456789',
            'is_active' => 'ya',
        ],
    ],
    'cabor' => [
        'label' => 'Cabang Olahraga',
        'model' => \App\Models\Cabor::class,
        'storage_dir' => null,
        'route_index' => 'admin.cabor.index',
        'headers' => [
            'kode' => 'Kode *',
            'name' => 'Nama Cabor *',
            'description' => 'Deskripsi',
            'is_active' => 'Aktif (ya/tidak)',
        ],
        'example' => [
            'kode' => 'CAB-2026-003',
            'name' => 'Voli',
            'description' => 'Cabang voli',
            'is_active' => 'ya',
        ],
    ],
];
